### PR TITLE
Google Analytics Installed for Pragma 2018

### PR DESCRIPTION
**Pull request by aadixiiita**
Added the tracking ID script in index.html .

### CODE REVIEW

**Comment by pradeepgangwar** [comment]
Update your branch with master and update this PR. Remove all occurrences of DevCon and replace then with Pragma.

**Comment by bobyshukla** [comment]
Ok

**Comment by aadixiiita** [comment]
Ok

**Comment by aadixiiita** [comment]
Live Link -: http://aadishukla.me/Pragma/

**Pull request merged**
